version: '3.3'

services:
    mysqldb:
        image: mysql:latest
        volumes:
            - db_data:/var/lib/mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: samplepassword
            MYSQL_DATABASE: wordpressdocker
            MYSQL_USER: wordpressdocker
            MYSQL_PASSWORD: wordpressdocker
    phpmyadmin:
        depends_on:
            - mysqldb
        image: phpmyadmin/phpmyadmin
        ports:
            - 8080:80
        environment:
            PMA_HOST: mysqldb
            MYSQL_ROOT_PASSWORD: samplepasswor
    wordpress:
        depends_on:
            - mysqldb
        image: wordpress:latest
        ports:
            - 8080:80
        restart: always
        environment:
            WORDPRESS_DB_HOST: mysqldb:3306
            WORDPRESS_DB_USER: wordpressdocker
            WORDPRESS_DB_PASSWORD: wordpressdocker
volumes:
    db_data: