version: '3.3'

services:
    mysqldb:
        image: mysql:latest
        volumes:
            - db_data:/var/lib/mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: samplepassword
            MYSQL_DATABASE: wordpressdocker
            MYSQL_USER: wordpressdocker
            MYSQL_PASSWORD: wordpressdocker
        networks:
            - wordpressdocker_n
    phpmyadmin:
        depends_on:
            - mysqldb
        image: phpmyadmin/phpmyadmin
        ports:
            - 9000:80
        environment:
            PMA_HOST: mysqldb
            MYSQL_ROOT_PASSWORD: samplepassword
        networks:
            - wordpressdocker_n
    wordpress:
        depends_on:
            - mysqldb
        image: wordpress:latest
        ports:
            - 80:80
        restart: always
        volumes:
            - ./wp-content:/var/www/wp/wp-content
        environment:
            WORDPRESS_DB_HOST: mysqldb:3306
            WORDPRESS_DB_USER: wordpressdocker
            WORDPRESS_DB_PASSWORD: wordpressdocker
        networks:
            - wordpressdocker_n
networks:
    wordpressdocker_n:
volumes:
    db_data: