version: '3.3'

services:
    mysqldb:
        image: mysql:latest
        volumes:
            - db_data:/var/lib/mysql
        restart: always
        secrets:
            - file_sec
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        networks:
            - isolated_network
    phpmyadmin:
        depends_on:
            - mysqldb
        image: phpmyadmin/phpmyadmin
        ports:
            - "9000:80"
        secrets:
            - file_sec
        environment:
            PMA_HOST: mysqldb
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        networks:
            - isolated_network
    wordpress:
        depends_on:
            - mysqldb
        image: wordpress:latest
        ports:
            - "80:80"
        restart: always
        volumes:
            - .:/var/www/html/
        secrets:
            - file_sec
        environment:
            WORDPRESS_DB_HOST: mysqldb:3306
            WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
            WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
            WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
        networks:
            - isolated_network
networks:
    isolated_network:
volumes:
    db_data:
secrets:
    file_sec:
        file: .env